FROM oven/bun:latest AS build

WORKDIR /app

COPY . .

RUN bun install

RUN cd packages/generator && bun run build

FROM oven/bun:latest AS server

WORKDIR /app

COPY --from=build /app/packages/generator/generator ./

CMD ["./generator"]
