FROM oven/bun:latest AS build

WORKDIR /app

COPY . .

RUN bun install

RUN cd packages/backend && bun run build

FROM oven/bun:latest AS server

WORKDIR /app

COPY --from=build /app/packages/backend/backend ./

EXPOSE 8000

CMD ["./backend"]
